### ISSUE TITLE
Doesn't seem to be working properly...

### ISSUE THREAD

**Issue by esenef74** [MGApcDev/Trello-Enhanced-Date#8]
This extension highlights ALL my dates with the last color in the list.  I've tried colors in forwards order and in reverse order.  Neither seem to work...

**Comment by MGApcDev** [comment]
Sorry, I don't know why I'm not receiving mails for this stuff.
Another user informed me that US English doesn't work, and you have to change the language to UK English.

If you're still using the extension, please get back to me and say if it worked.
